
CREATE DATABASE IF NOT EXISTS lc DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 10 库 0--9
CREATE DATABASE IF NOT EXISTS lc_0 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_1 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_2 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_3 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_4 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_5 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_6 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_7 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_8 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_9 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;


CREATE USER 'lc_rw'@'%' IDENTIFIED BY 'pass1';
GRANT ALL ON *.* TO 'lc_rw'@'%';

