-- 用于生成逻辑表的库，开发阶段使用
CREATE DATABASE IF NOT EXISTS lc_gen_test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 单库
CREATE DATABASE IF NOT EXISTS lc DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 10 库 0--9
CREATE DATABASE IF NOT EXISTS lc_00 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_01 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_02 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_03 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_04 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_05 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_06 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_07 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_08 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS lc_09 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;


CREATE USER 'lc_rw'@'%' IDENTIFIED BY 'pass1';
GRANT ALL ON *.* TO 'lc_rw'@'%';

